#!/bin/bash

pbs_server=casper-pbs
max_cpus=128
acc_var_dep=DAV_PROJECT
res_type="1 core"
pbs_opts[-q]=${arg_dict[-q]:-casper}

case ${pbs_opts[-q]} in
    casper*)
        pbs_opts['-l select']=":mem=${mem:-10GB}"

        if [[ $my_name == qcmd ]]; then
            pbs_opts['-l walltime']=01:00:00
        else
            pbs_opts['-l walltime']=06:00:00
        fi

        if [[ ${ngpus:-1} -gt 1 ]]; then
            def_gpu=cc70
        else
            def_gpu=vis
        fi
        ;;
    gpudev*)
        max_cpus=36
        pbs_opts['-l walltime']=00:30:00
        pbs_opts['-l select']=":mem=${mem:-150GB}:ngpus=${ngpus:-1}:gpu_type=${gpu:-v100}"
        ;;
    *)
        pbs_opts['-l walltime']=01:00:00
        pbs_opts['-l select']=":mem=${mem:-10GB}"

        if [[ ${ngpus:-0} -gt 0 ]]; then
            def_mem=$((120 * ngpus))
            pbs_opts['-l select']=":mem=${mem:-${def_mem}GB}:ngpus=$ngpus"

            if [[ -n $gpu ]]; then
                pbs_opts['-l select']="${pbs_opts['-l select']}:gpu_type=$gpu"
            fi
        fi
        ;;
esac
