#!/bin/bash

case $NCAR_HOST in
    gust)
        pbs_server=gusched1
        ;;
    *)
        pbs_server=desched1
        ;;
esac

res_type="32 cores"
def_gpu=a100
max_cpus=64
pbs_opts['-l walltime']=01:00:00
pbs_opts[-q]=${arg_dict[-q]:-develop}

case ${pbs_opts[-q]} in
    develop*)
        if [[ ${ngpus:-0} -ge 1 ]]; then
            def_mem=$((120 * ngpus))
            def_ncpus=$((16 * ngpus))
            pbs_opts['-l select']=":mem=${mem:-${def_mem}GB}"
        else
            pbs_opts['-l select']=":mem=${mem:-55GB}"
            def_ncpus=32
        fi
        ;;
    *)
        if [[ ${ngpus:-0} -ge 1 ]]; then
            pbs_opts['-l select']=":mem=${mem:-487GB}"
            def_ncpus=64
        else
            pbs_opts['-l select']=":mem=${mem:-235GB}"
            def_ncpus=128
            max_cpus=128
        fi
        ;;
esac
